ENVIRONMENT:
  MAX_EPISODE_STEPS: 1001
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 10000
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
  ACTION_SPACE_CONFIG: "pyrobotnoisy"
  NOISE_MODEL:
    ROBOT: 'LoCoBot'
    CONTROLLER: 'ILQR'
    NOISE_MULTIPLIER: 1.0
TASK:
  TYPE: Exp-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SENSORS: ['NOISY_POSE_SENSOR', 'GT_POSE_SENSOR', 'GT_EGO_MAP_ANTICIPATED', 'COLLISION_SENSOR']
  GT_EGO_MAP_ANTICIPATED:
    MAP_SIZE: 101
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [0.2, 1.5]
    MAX_SENSOR_RANGE: 5.05
    NUM_TOPDOWN_MAP_SAMPLE_POINTS: 20000
    GT_TYPE: 'wall_occupancy'
    ALL_MAPS_INFO_PATH: 'data/datasets/exploration/gibson/v1/train/occant_gt_maps/all_maps_info.json'
  MEASUREMENTS: []
DATASET:
  TYPE: Exploration-v1
  SPLIT: train
  DATA_PATH: data/datasets/exploration/gibson/v1/{split}/{split}.json.gz
