ENVIRONMENT:
  MAX_EPISODE_STEPS: 100
  ITERATOR_OPTIONS:
    SHUFFLE: False
    GROUP_BY_SCENE: True
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  DEPTH_SENSOR:
    WIDTH: 400
    HEIGHT: 400
TASK:
  TYPE: Exp-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SENSORS: ['GT_POSE_SENSOR', 'NOISY_POSE_SENSOR', 'GT_EGO_MAP', 'GT_EGO_MAP_ANTICIPATED']
  NOISY_POSE_SENSOR:
    NOISE_SCALING: 0.1
  GT_EGO_MAP:
    MAP_SIZE: 101
    MAP_SCALE: 0.05
    MAX_SENSOR_RANGE: 3.25
    HEIGHT_THRESH: [0.2, 1.5]
  GT_EGO_MAP_ANTICIPATED:
    MAP_SIZE: 101
    MAP_SCALE: 0.05
    MAX_SENSOR_RANGE: 5.05
    HEIGHT_THRESH: [0.2, 1.5]
  MEASUREMENTS: ['TOP_DOWN_MAP_EXP', 'GT_GLOBAL_MAP']
DATASET:
  TYPE: Exploration-v1
  SPLIT: val
  DATA_PATH: data/datasets/exploration/gibson/v1/{split}/{split}.json.gz
